-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:9ddd34cc5db4c9bb3e06d7dc138f3dca:1/1$
-- 

return {
	texture = 'gameplay.atlas.png',
	frames = {
			{
				name = "bomb_round_30fps_00001.png",
				spriteColorRect = { x = 69, y = 86, width = 90, height = 74 },
				uvRect = { u0 = 0.919697, v0 = 0.203922, u1 = 0.987879, v1 = 0.34902 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00002.png",
				spriteColorRect = { x = 66, y = 71, width = 100, height = 104 },
				uvRect = { u0 = 0.919697, v0 = 0.00392157, u1 = 0.998485, v1 = 0.2 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00003.png",
				spriteColorRect = { x = 58, y = 57, width = 120, height = 128 },
				uvRect = { u0 = 0.907576, v0 = 0.705882, u1 = 0.998485, v1 = 0.956863 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00004.png",
				spriteColorRect = { x = 47, y = 52, width = 148, height = 148 },
				uvRect = { u0 = 0.793939, v0 = 0.705882, u1 = 0.906061, v1 = 0.996078 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00005.png",
				spriteColorRect = { x = 30, y = 35, width = 186, height = 160 },
				uvRect = { u0 = 0.79697, v0 = 0.00392157, u1 = 0.918182, v1 = 0.368627 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00006.png",
				spriteColorRect = { x = 21, y = 31, width = 184, height = 168 },
				uvRect = { u0 = 0.793939, v0 = 0.372549, u1 = 0.933333, v1 = 0.701961 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00007.png",
				spriteColorRect = { x = 31, y = 40, width = 186, height = 176 },
				uvRect = { u0 = 0.662121, v0 = 0.00392157, u1 = 0.795455, v1 = 0.368627 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00008.png",
				spriteColorRect = { x = 18, y = 27, width = 212, height = 196 },
				uvRect = { u0 = 0.643939, v0 = 0.435294, u1 = 0.792424, v1 = 0.85098 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00009.png",
				spriteColorRect = { x = 25, y = 3, width = 204, height = 218 },
				uvRect = { u0 = 0.506061, v0 = 0.00392157, u1 = 0.660606, v1 = 0.431373 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00010.png",
				spriteColorRect = { x = 17, y = 12, width = 220, height = 214 },
				uvRect = { u0 = 0.342424, v0 = 0.00392157, u1 = 0.504545, v1 = 0.435294 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00011.png",
				spriteColorRect = { x = 3, y = 0, width = 218, height = 216 },
				uvRect = { u0 = 0.319697, v0 = 0.478431, u1 = 0.483333, v1 = 0.905882 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00012.png",
				spriteColorRect = { x = 7, y = 9, width = 208, height = 218 },
				uvRect = { u0 = 0.484848, v0 = 0.439216, u1 = 0.642424, v1 = 0.866667 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00013.png",
				spriteColorRect = { x = 10, y = 0, width = 206, height = 240 },
				uvRect = { u0 = 0.162121, v0 = 0.478431, u1 = 0.318182, v1 = 0.94902 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00014.png",
				spriteColorRect = { x = 8, y = 0, width = 210, height = 238 },
				uvRect = { u0 = 0.00151515, v0 = 0.478431, u1 = 0.160606, v1 = 0.945098 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00015.png",
				spriteColorRect = { x = 0, y = 23, width = 240, height = 206 },
				uvRect = { u0 = 0.184848, v0 = 0.00392157, u1 = 0.340909, v1 = 0.47451 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00016.png",
				spriteColorRect = { x = 0, y = 0, width = 240, height = 240 },
				uvRect = { u0 = 0.00151515, v0 = 0.00392157, u1 = 0.183333, v1 = 0.47451 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

