-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:873a78604b245e506c53a6bfc210b61e:1/1$
-- 

return {
	texture = 'gameplay.atlas.png',
	frames = {
			{
				name = "1_be.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.880137, v0 = 0.929043, u1 = 0.91047, v1 = 0.963146 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1_gn.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 63 },
				uvRect = { u0 = 0.886497, v0 = 0.779978, u1 = 0.917319, v1 = 0.814631 },
				spriteSourceSize = { width = 63, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1_pe.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.880137, v0 = 0.893839, u1 = 0.91047, v1 = 0.927943 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1_pk.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.848826, v0 = 0.956546, u1 = 0.879159, v1 = 0.990649 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1_rd.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 63 },
				uvRect = { u0 = 0.918297, v0 = 0.788229, u1 = 0.949119, v1 = 0.822332 },
				spriteSourceSize = { width = 62, height = 63 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "2_be.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.817515, v0 = 0.956546, u1 = 0.847847, v1 = 0.990649 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2_gn.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 63 },
				uvRect = { u0 = 0.965753, v0 = 0.752475, u1 = 0.996575, v1 = 0.787129 },
				spriteSourceSize = { width = 63, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2_pe.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.848826, v0 = 0.921342, u1 = 0.879159, v1 = 0.955446 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2_pk.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.817515, v0 = 0.921342, u1 = 0.847847, v1 = 0.955446 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2_rd.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 63 },
				uvRect = { u0 = 0.854697, v0 = 0.779978, u1 = 0.885519, v1 = 0.814081 },
				spriteSourceSize = { width = 62, height = 63 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "3_be.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.84589, v0 = 0.886139, u1 = 0.876223, v1 = 0.920242 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3_gn.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 63 },
				uvRect = { u0 = 0.782779, v0 = 0.913091, u1 = 0.813601, v1 = 0.947745 },
				spriteSourceSize = { width = 63, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3_pe.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.814579, v0 = 0.886139, u1 = 0.844912, v1 = 0.920242 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3_pk.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.96135, v0 = 0.858636, u1 = 0.991683, v1 = 0.892739 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3_rd.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 63 },
				uvRect = { u0 = 0.786204, v0 = 0.948845, u1 = 0.816536, v1 = 0.983498 },
				spriteSourceSize = { width = 62, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4_be.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.930039, v0 = 0.858636, u1 = 0.960372, v1 = 0.892739 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4_gn.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 63 },
				uvRect = { u0 = 0.772994, v0 = 0.842134, u1 = 0.803816, v1 = 0.876788 },
				spriteSourceSize = { width = 63, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4_pe.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.898728, v0 = 0.858636, u1 = 0.929061, v1 = 0.892739 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4_pk.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.867417, v0 = 0.850935, u1 = 0.89775, v1 = 0.885039 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4_rd.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 63 },
				uvRect = { u0 = 0.772994, v0 = 0.877888, u1 = 0.803816, v1 = 0.911991 },
				spriteSourceSize = { width = 62, height = 63 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "5_be.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.836106, v0 = 0.850935, u1 = 0.866438, v1 = 0.885039 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5_gn.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 63 },
				uvRect = { u0 = 0.965753, v0 = 0.716722, u1 = 0.996575, v1 = 0.751375 },
				spriteSourceSize = { width = 63, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5_pe.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.942759, v0 = 0.823432, u1 = 0.973092, v1 = 0.857536 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5_pk.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.911448, v0 = 0.823432, u1 = 0.941781, v1 = 0.857536 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5_rd.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 63 },
				uvRect = { u0 = 0.772505, v0 = 0.806381, u1 = 0.802838, v1 = 0.841034 },
				spriteSourceSize = { width = 62, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6_be.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.804795, v0 = 0.850935, u1 = 0.835127, v1 = 0.885039 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6_gn.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 63 },
				uvRect = { u0 = 0.933953, v0 = 0.720022, u1 = 0.964775, v1 = 0.754675 },
				spriteSourceSize = { width = 63, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6_pe.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.880137, v0 = 0.815732, u1 = 0.91047, v1 = 0.849835 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6_pk.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.848826, v0 = 0.815182, u1 = 0.879159, v1 = 0.849285 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6_rd.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 63 },
				uvRect = { u0 = 0.965753, v0 = 0.680968, u1 = 0.996086, v1 = 0.715622 },
				spriteSourceSize = { width = 62, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7_be.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.880137, v0 = 0.964246, u1 = 0.909491, v1 = 0.99725 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7_gn.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.941781, v0 = 0.927943, u1 = 0.971135, v1 = 0.960946 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7_pe.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.941781, v0 = 0.893839, u1 = 0.971135, v1 = 0.926843 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7_pk.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.911448, v0 = 0.927943, u1 = 0.940802, v1 = 0.960946 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7_rd.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.911448, v0 = 0.893839, u1 = 0.940802, v1 = 0.926843 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ball_level_bg.png",
				spriteColorRect = { x = 0, y = 0, width = 69, height = 70 },
				uvRect = { u0 = 0.654599, v0 = 0.769527, u1 = 0.688845, v1 = 0.807481 },
				spriteSourceSize = { width = 69, height = 70 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "ball_level_mask.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 53 },
				uvRect = { u0 = 0.399706, v0 = 0.969747, u1 = 0.426614, v1 = 0.9989 },
				spriteSourceSize = { width = 55, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "black_dj_1.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 56 },
				uvRect = { u0 = 0.939824, v0 = 0.962046, u1 = 0.967221, v1 = 0.992299 },
				spriteSourceSize = { width = 55, height = 56 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "black_dj_2.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 11 },
				uvRect = { u0 = 0.274951, v0 = 0.814081, u1 = 0.280333, v1 = 0.844334 },
				spriteSourceSize = { width = 55, height = 13 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "blue_dj_1.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 56 },
				uvRect = { u0 = 0.911448, v0 = 0.962046, u1 = 0.938845, v1 = 0.992299 },
				spriteSourceSize = { width = 55, height = 56 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "blue_dj_2.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 11 },
				uvRect = { u0 = 0.438356, v0 = 0.535204, u1 = 0.443738, v1 = 0.566007 },
				spriteSourceSize = { width = 56, height = 13 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_black.png",
				spriteColorRect = { x = 2, y = 2, width = 73, height = 75 },
				uvRect = { u0 = 0.735812, v0 = 0.808031, u1 = 0.771526, v1 = 0.849285 },
				spriteSourceSize = { width = 75, height = 77 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_blue.png",
				spriteColorRect = { x = 2, y = 2, width = 73, height = 75 },
				uvRect = { u0 = 0.891389, v0 = 0.737624, u1 = 0.927104, v1 = 0.778878 },
				spriteSourceSize = { width = 75, height = 77 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_effect_30fps_00001.png",
				spriteColorRect = { x = 28, y = 26, width = 72, height = 72 },
				uvRect = { u0 = 0.736791, v0 = 0.850385, u1 = 0.772016, v1 = 0.889989 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_effect_30fps_00002.png",
				spriteColorRect = { x = 28, y = 26, width = 72, height = 72 },
				uvRect = { u0 = 0.736791, v0 = 0.850385, u1 = 0.772016, v1 = 0.889989 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_effect_30fps_00003.png",
				spriteColorRect = { x = 26, y = 30, width = 72, height = 66 },
				uvRect = { u0 = 0.72407, v0 = 0.770627, u1 = 0.759295, v1 = 0.806931 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_effect_30fps_00004.png",
				spriteColorRect = { x = 26, y = 30, width = 72, height = 66 },
				uvRect = { u0 = 0.72407, v0 = 0.770627, u1 = 0.759295, v1 = 0.806931 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_effect_30fps_00005.png",
				spriteColorRect = { x = 26, y = 27, width = 74, height = 74 },
				uvRect = { u0 = 0.895793, v0 = 0.624312, u1 = 0.931996, v1 = 0.665017 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_effect_30fps_00006.png",
				spriteColorRect = { x = 26, y = 27, width = 74, height = 74 },
				uvRect = { u0 = 0.895793, v0 = 0.624312, u1 = 0.931996, v1 = 0.665017 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_effect_30fps_00007.png",
				spriteColorRect = { x = 25, y = 27, width = 70, height = 70 },
				uvRect = { u0 = 0.736791, v0 = 0.891089, u1 = 0.771037, v1 = 0.929593 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_effect_30fps_00008.png",
				spriteColorRect = { x = 25, y = 27, width = 70, height = 70 },
				uvRect = { u0 = 0.736791, v0 = 0.891089, u1 = 0.771037, v1 = 0.929593 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_line_30fps_00001.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 128 },
				uvRect = { u0 = 0.527397, v0 = 0.768977, u1 = 0.59002, v1 = 0.786579 },
				spriteSourceSize = { width = 32, height = 128 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "bomb_color_line_30fps_00002.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 128 },
				uvRect = { u0 = 0.978963, v0 = 0.00110011, u1 = 0.994618, v1 = 0.0715072 },
				spriteSourceSize = { width = 32, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bomb_color_line_30fps_00003.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 128 },
				uvRect = { u0 = 0.527397, v0 = 0.768977, u1 = 0.59002, v1 = 0.786579 },
				spriteSourceSize = { width = 32, height = 128 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "bomb_color_line_30fps_00004.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 128 },
				uvRect = { u0 = 0.978963, v0 = 0.00110011, u1 = 0.994618, v1 = 0.0715072 },
				spriteSourceSize = { width = 32, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bomb_color_thunder_30fps_00000.png",
				spriteColorRect = { x = 18, y = 0, width = 52, height = 89 },
				uvRect = { u0 = 0.427593, v0 = 0.969747, u1 = 0.471135, v1 = 0.99835 },
				spriteSourceSize = { width = 92, height = 93 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_color_thunder_30fps_00001.png",
				spriteColorRect = { x = 24, y = 0, width = 42, height = 93 },
				uvRect = { u0 = 0.978474, v0 = 0.218922, u1 = 0.999022, v1 = 0.270077 },
				spriteSourceSize = { width = 92, height = 93 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_color_thunder_30fps_00002.png",
				spriteColorRect = { x = 18, y = 2, width = 48, height = 91 },
				uvRect = { u0 = 0.932975, v0 = 0.653465, u1 = 0.977495, v1 = 0.679868 },
				spriteSourceSize = { width = 92, height = 93 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_green.png",
				spriteColorRect = { x = 2, y = 2, width = 73, height = 75 },
				uvRect = { u0 = 0.854697, v0 = 0.737624, u1 = 0.890411, v1 = 0.778878 },
				spriteSourceSize = { width = 75, height = 77 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 71 },
				uvRect = { u0 = 0.751468, v0 = 0.930693, u1 = 0.7818, v1 = 0.969747 },
				spriteSourceSize = { width = 62, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bomb_line_effect_30fps_00001.png",
				spriteColorRect = { x = 175, y = 173, width = 50, height = 50 },
				uvRect = { u0 = 0.87818, v0 = 0.666117, u1 = 0.902642, v1 = 0.693619 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_effect_30fps_00002.png",
				spriteColorRect = { x = 149, y = 148, width = 104, height = 102 },
				uvRect = { u0 = 0.723092, v0 = 0.446645, u1 = 0.772994, v1 = 0.50385 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_line_effect_30fps_00003.png",
				spriteColorRect = { x = 121, y = 119, width = 160, height = 160 },
				uvRect = { u0 = 0.853718, v0 = 0.413091, u1 = 0.931996, v1 = 0.5011 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_effect_30fps_00004.png",
				spriteColorRect = { x = 96, y = 94, width = 212, height = 212 },
				uvRect = { u0 = 0.386008, v0 = 0.852035, u1 = 0.489726, v1 = 0.968647 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_effect_30fps_00005.png",
				spriteColorRect = { x = 71, y = 69, width = 262, height = 262 },
				uvRect = { u0 = 0.285714, v0 = 0.706821, u1 = 0.413894, v1 = 0.850935 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_effect_30fps_00006.png",
				spriteColorRect = { x = 48, y = 46, width = 310, height = 310 },
				uvRect = { u0 = 0.285714, v0 = 0.535204, u1 = 0.437378, v1 = 0.705721 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_effect_30fps_00007.png",
				spriteColorRect = { x = 27, y = 25, width = 352, height = 352 },
				uvRect = { u0 = 0.271526, v0 = 0.340484, u1 = 0.443738, v1 = 0.534103 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_effect_30fps_00008.png",
				spriteColorRect = { x = 16, y = 18, width = 374, height = 368 },
				uvRect = { u0 = 0.104697, v0 = 0.607261, u1 = 0.284736, v1 = 0.812981 },
				spriteSourceSize = { width = 400, height = 400 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_line_ray_30fps_00001.png",
				spriteColorRect = { x = 34, y = 729, width = 26, height = 70 },
				uvRect = { u0 = 0.271526, v0 = 0.535204, u1 = 0.284247, v1 = 0.573707 },
				spriteSourceSize = { width = 100, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_ray_30fps_00002.png",
				spriteColorRect = { x = 21, y = 643, width = 52, height = 142 },
				uvRect = { u0 = 0.267613, v0 = 0.966447, u1 = 0.337084, v1 = 0.99505 },
				spriteSourceSize = { width = 100, height = 800 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_line_ray_30fps_00003.png",
				spriteColorRect = { x = 9, y = 558, width = 78, height = 220 },
				uvRect = { u0 = 0.414873, v0 = 0.706821, u1 = 0.453033, v1 = 0.827833 },
				spriteSourceSize = { width = 100, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_ray_30fps_00004.png",
				spriteColorRect = { x = 16, y = 418, width = 64, height = 346 },
				uvRect = { u0 = 0.104697, v0 = 0.814081, u1 = 0.273973, v1 = 0.849285 },
				spriteSourceSize = { width = 100, height = 800 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_line_ray_30fps_00005.png",
				spriteColorRect = { x = 16, y = 277, width = 62, height = 498 },
				uvRect = { u0 = 0.444716, v0 = 0.338834, u1 = 0.475049, v1 = 0.612761 },
				spriteSourceSize = { width = 100, height = 800 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_line_ray_30fps_00006.png",
				spriteColorRect = { x = 24, y = 150, width = 48, height = 602 },
				uvRect = { u0 = 0.317515, v0 = 0.19692, u1 = 0.612035, v1 = 0.223322 },
				spriteSourceSize = { width = 100, height = 800 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_line_ray_30fps_00007.png",
				spriteColorRect = { x = 27, y = 20, width = 40, height = 752 },
				uvRect = { u0 = 0.317515, v0 = 0.117712, u1 = 0.685421, v1 = 0.139714 },
				spriteSourceSize = { width = 100, height = 800 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_pink.png",
				spriteColorRect = { x = 2, y = 2, width = 73, height = 75 },
				uvRect = { u0 = 0.714775, v0 = 0.943894, u1 = 0.750489, v1 = 0.985149 },
				spriteSourceSize = { width = 75, height = 77 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_red.png",
				spriteColorRect = { x = 2, y = 2, width = 73, height = 75 },
				uvRect = { u0 = 0.678082, v0 = 0.947195, u1 = 0.713796, v1 = 0.988449 },
				spriteSourceSize = { width = 75, height = 77 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round.png",
				spriteColorRect = { x = 7, y = 5, width = 63, height = 69 },
				uvRect = { u0 = 0.933953, v0 = 0.680968, u1 = 0.964775, v1 = 0.718922 },
				spriteSourceSize = { width = 75, height = 77 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00001.png",
				spriteColorRect = { x = 69, y = 86, width = 90, height = 74 },
				uvRect = { u0 = 0.895793, v0 = 0.573707, u1 = 0.931996, v1 = 0.623212 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00002.png",
				spriteColorRect = { x = 66, y = 71, width = 100, height = 104 },
				uvRect = { u0 = 0.67319, v0 = 0.445545, u1 = 0.722114, v1 = 0.50275 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00003.png",
				spriteColorRect = { x = 58, y = 57, width = 120, height = 128 },
				uvRect = { u0 = 0.454012, v0 = 0.784928, u1 = 0.516634, v1 = 0.850935 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00004.png",
				spriteColorRect = { x = 47, y = 52, width = 148, height = 148 },
				uvRect = { u0 = 0.454012, v0 = 0.70242, u1 = 0.526419, v1 = 0.783828 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00005.png",
				spriteColorRect = { x = 30, y = 35, width = 186, height = 160 },
				uvRect = { u0 = 0.644325, v0 = 0.342134, u1 = 0.722603, v1 = 0.444444 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00006.png",
				spriteColorRect = { x = 21, y = 31, width = 184, height = 168 },
				uvRect = { u0 = 0.770059, v0 = 0.228823, u1 = 0.860078, v1 = 0.321232 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00007.png",
				spriteColorRect = { x = 31, y = 40, width = 186, height = 176 },
				uvRect = { u0 = 0.898728, v0 = 0.115512, u1 = 0.984834, v1 = 0.217822 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00008.png",
				spriteColorRect = { x = 18, y = 27, width = 212, height = 196 },
				uvRect = { u0 = 0.686399, v0 = 0.117712, u1 = 0.790117, v1 = 0.225523 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00009.png",
				spriteColorRect = { x = 25, y = 3, width = 204, height = 218 },
				uvRect = { u0 = 0.791096, v0 = 0.115512, u1 = 0.89775, v1 = 0.227723 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00010.png",
				spriteColorRect = { x = 17, y = 12, width = 220, height = 214 },
				uvRect = { u0 = 0.000978474, v0 = 0.869637, u1 = 0.105675, v1 = 0.990649 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00011.png",
				spriteColorRect = { x = 3, y = 0, width = 218, height = 216 },
				uvRect = { u0 = 0.506849, v0 = 0.224422, u1 = 0.613503, v1 = 0.343234 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00012.png",
				spriteColorRect = { x = 7, y = 9, width = 208, height = 218 },
				uvRect = { u0 = 0.614481, v0 = 0.226623, u1 = 0.721135, v1 = 0.341034 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bomb_round_30fps_00013.png",
				spriteColorRect = { x = 10, y = 0, width = 206, height = 240 },
				uvRect = { u0 = 0.106654, v0 = 0.850385, u1 = 0.207436, v1 = 0.982398 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00014.png",
				spriteColorRect = { x = 8, y = 0, width = 210, height = 238 },
				uvRect = { u0 = 0.476027, v0 = 0.477448, u1 = 0.578767, v1 = 0.608361 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00015.png",
				spriteColorRect = { x = 0, y = 23, width = 240, height = 206 },
				uvRect = { u0 = 0.267613, v0 = 0.852035, u1 = 0.385029, v1 = 0.965347 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bomb_round_30fps_00016.png",
				spriteColorRect = { x = 0, y = 0, width = 240, height = 240 },
				uvRect = { u0 = 0.476027, v0 = 0.344334, u1 = 0.593444, v1 = 0.476348 },
				spriteSourceSize = { width = 240, height = 240 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bs_ts_1.png",
				spriteColorRect = { x = 3, y = 7, width = 385, height = 206 },
				uvRect = { u0 = 0.317515, v0 = 0.224422, u1 = 0.505871, v1 = 0.337734 },
				spriteSourceSize = { width = 391, height = 216 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bs_ts_2.png",
				spriteColorRect = { x = 2, y = 8, width = 201, height = 96 },
				uvRect = { u0 = 0.722114, v0 = 0.226623, u1 = 0.76908, v1 = 0.337184 },
				spriteSourceSize = { width = 219, height = 120 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "control_panel.png",
				spriteColorRect = { x = 0, y = 0, width = 645, height = 615 },
				uvRect = { u0 = 0.000978474, v0 = 0.00110011, u1 = 0.316536, v1 = 0.339384 },
				spriteSourceSize = { width = 645, height = 615 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dj_1.png",
				spriteColorRect = { x = 0, y = 0, width = 68, height = 67 },
				uvRect = { u0 = 0.689824, v0 = 0.770627, u1 = 0.723092, v1 = 0.807481 },
				spriteSourceSize = { width = 68, height = 67 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "energy.png",
				spriteColorRect = { x = 2, y = 4, width = 82, height = 30 },
				uvRect = { u0 = 0.571429, v0 = 0.787679, u1 = 0.586106, v1 = 0.832783 },
				spriteSourceSize = { width = 86, height = 38 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "energy_bar.png",
				spriteColorRect = { x = 0, y = 0, width = 171, height = 75 },
				uvRect = { u0 = 0.861057, v0 = 0.228823, u1 = 0.89775, v1 = 0.322882 },
				spriteSourceSize = { width = 171, height = 75 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "explosion_fly3_15fps_0000.png",
				spriteColorRect = { x = 41, y = 33, width = 99, height = 109 },
				uvRect = { u0 = 0.631605, v0 = 0.140814, u1 = 0.684932, v1 = 0.19527 },
				spriteSourceSize = { width = 165, height = 165 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "explosion_fly3_15fps_0001.png",
				spriteColorRect = { x = 4, y = 2, width = 159, height = 161 },
				uvRect = { u0 = 0.773973, v0 = 0.411991, u1 = 0.85274, v1 = 0.49945 },
				spriteSourceSize = { width = 165, height = 165 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "explosion_fly3_15fps_0002.png",
				spriteColorRect = { x = 2, y = 2, width = 161, height = 161 },
				uvRect = { u0 = 0.898728, v0 = 0.218922, u1 = 0.977495, v1 = 0.307481 },
				spriteSourceSize = { width = 165, height = 165 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "explosion_fly3_15fps_0003.png",
				spriteColorRect = { x = 2, y = 2, width = 161, height = 161 },
				uvRect = { u0 = 0.773973, v0 = 0.322332, u1 = 0.85274, v1 = 0.410891 },
				spriteSourceSize = { width = 165, height = 165 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "explosion_fly3_15fps_0004.png",
				spriteColorRect = { x = 3, y = 4, width = 153, height = 159 },
				uvRect = { u0 = 0.438356, v0 = 0.613861, u1 = 0.513209, v1 = 0.70132 },
				spriteSourceSize = { width = 165, height = 165 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "explosion_fly3_15fps_0005.png",
				spriteColorRect = { x = 27, y = 12, width = 129, height = 121 },
				uvRect = { u0 = 0.932975, v0 = 0.391089, u1 = 0.992172, v1 = 0.462046 },
				spriteSourceSize = { width = 165, height = 165 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "game_score.png",
				spriteColorRect = { x = 0, y = 0, width = 210, height = 75 },
				uvRect = { u0 = 0.579746, v0 = 0.477448, u1 = 0.616438, v1 = 0.592959 },
				spriteSourceSize = { width = 210, height = 75 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "gjxiang_small.png",
				spriteColorRect = { x = 0, y = 0, width = 69, height = 50 },
				uvRect = { u0 = 0.751468, v0 = 0.970847, u1 = 0.785225, v1 = 0.99835 },
				spriteSourceSize = { width = 69, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "green_dj_1.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 56 },
				uvRect = { u0 = 0.972114, v0 = 0.957646, u1 = 0.999022, v1 = 0.988449 },
				spriteSourceSize = { width = 55, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "green_dj_2.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 11 },
				uvRect = { u0 = 0.73728, v0 = 0.763476, u1 = 0.764188, v1 = 0.769527 },
				spriteSourceSize = { width = 55, height = 13 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hit_30fps_0000.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.719667, v0 = 0.576458, u1 = 0.78229, v1 = 0.646865 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0001.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.656067, v0 = 0.654015, u1 = 0.718689, v1 = 0.724422 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0002.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.656067, v0 = 0.582508, u1 = 0.718689, v1 = 0.652915 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0003.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.591977, v0 = 0.880088, u1 = 0.654599, v1 = 0.950495 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0004.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.591977, v0 = 0.808581, u1 = 0.654599, v1 = 0.878988 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0005.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.590998, v0 = 0.737074, u1 = 0.65362, v1 = 0.807481 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0006.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.592466, v0 = 0.665567, u1 = 0.655088, v1 = 0.735974 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0007.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.592466, v0 = 0.594059, u1 = 0.655088, v1 = 0.664466 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0008.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.528376, v0 = 0.919692, u1 = 0.590998, v1 = 0.990099 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0009.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.528376, v0 = 0.848185, u1 = 0.590998, v1 = 0.918592 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0010.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.932975, v0 = 0.534653, u1 = 0.995597, v1 = 0.605061 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0011.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.841487, v0 = 0.5022, u1 = 0.90411, v1 = 0.572607 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0012.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.777886, v0 = 0.50055, u1 = 0.840509, v1 = 0.570957 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0013.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.714286, v0 = 0.50495, u1 = 0.776908, v1 = 0.575358 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0014.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.932975, v0 = 0.463146, u1 = 0.995597, v1 = 0.533553 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hit_30fps_0015.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.527397, v0 = 0.69747, u1 = 0.59002, v1 = 0.767877 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ks_sz_1.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 115 },
				uvRect = { u0 = 0.905088, v0 = 0.5022, u1 = 0.931996, v1 = 0.565457 },
				spriteSourceSize = { width = 55, height = 115 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ks_sz_2.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 118 },
				uvRect = { u0 = 0.932975, v0 = 0.606161, u1 = 0.990705, v1 = 0.652365 },
				spriteSourceSize = { width = 84, height = 118 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "ks_sz_3.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 121 },
				uvRect = { u0 = 0.67319, v0 = 0.50385, u1 = 0.713307, v1 = 0.570407 },
				spriteSourceSize = { width = 82, height = 121 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ks_sz_go.png",
				spriteColorRect = { x = 0, y = 0, width = 253, height = 119 },
				uvRect = { u0 = 0.208415, v0 = 0.850385, u1 = 0.266634, v1 = 0.989549 },
				spriteSourceSize = { width = 253, height = 119 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "light_blue.png",
				spriteColorRect = { x = 25, y = 0, width = 210, height = 960 },
				uvRect = { u0 = 0.317515, v0 = 0.00110011, u1 = 0.787182, v1 = 0.116612 },
				spriteSourceSize = { width = 256, height = 1024 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "light_yellow.png",
				spriteColorRect = { x = 25, y = 0, width = 210, height = 960 },
				uvRect = { u0 = 0.000978474, v0 = 0.340484, u1 = 0.103718, v1 = 0.868537 },
				spriteSourceSize = { width = 256, height = 1024 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lv_1.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 57 },
				uvRect = { u0 = 0.928082, v0 = 0.755776, u1 = 0.959393, v1 = 0.787129 },
				spriteSourceSize = { width = 64, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lv_2.png",
				spriteColorRect = { x = 0, y = 0, width = 59, height = 54 },
				uvRect = { u0 = 0.905577, v0 = 0.666117, u1 = 0.931996, v1 = 0.69857 },
				spriteSourceSize = { width = 59, height = 54 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "lv_3.png",
				spriteColorRect = { x = 0, y = 0, width = 63, height = 50 },
				uvRect = { u0 = 0.760274, v0 = 0.777778, u1 = 0.791096, v1 = 0.805281 },
				spriteSourceSize = { width = 63, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lv_4.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 62 },
				uvRect = { u0 = 0.817515, v0 = 0.815732, u1 = 0.847847, v1 = 0.849835 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lv_5.png",
				spriteColorRect = { x = 0, y = 0, width = 59, height = 58 },
				uvRect = { u0 = 0.338063, v0 = 0.966447, u1 = 0.366438, v1 = 0.9989 },
				spriteSourceSize = { width = 59, height = 58 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "lx_ts_1.png",
				spriteColorRect = { x = 4, y = 0, width = 388, height = 206 },
				uvRect = { u0 = 0.78816, v0 = 0.00110011, u1 = 0.977984, v1 = 0.114411 },
				spriteSourceSize = { width = 392, height = 208 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lx_ts_2.png",
				spriteColorRect = { x = 1, y = 6, width = 220, height = 100 },
				uvRect = { u0 = 0.594423, v0 = 0.344334, u1 = 0.643346, v1 = 0.465347 },
				spriteSourceSize = { width = 226, height = 108 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "monster_title.png",
				spriteColorRect = { x = 0, y = 0, width = 71, height = 37 },
				uvRect = { u0 = 0.414873, v0 = 0.828933, u1 = 0.449609, v1 = 0.849285 },
				spriteSourceSize = { width = 71, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pause_a.png",
				spriteColorRect = { x = 11, y = 8, width = 75, height = 75 },
				uvRect = { u0 = 0.490705, v0 = 0.934543, u1 = 0.527397, v1 = 0.975798 },
				spriteSourceSize = { width = 97, height = 97 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pink_dj_1.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 56 },
				uvRect = { u0 = 0.972114, v0 = 0.925743, u1 = 0.999022, v1 = 0.956546 },
				spriteSourceSize = { width = 55, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pink_dj_2.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 11 },
				uvRect = { u0 = 0.438356, v0 = 0.567107, u1 = 0.443738, v1 = 0.59736 },
				spriteSourceSize = { width = 55, height = 13 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "qiu_10.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.941781, v0 = 0.893839, u1 = 0.971135, v1 = 0.926843 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "qiu_6.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.911448, v0 = 0.927943, u1 = 0.940802, v1 = 0.960946 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "qiu_7.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.941781, v0 = 0.927943, u1 = 0.971135, v1 = 0.960946 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "qiu_8.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.911448, v0 = 0.893839, u1 = 0.940802, v1 = 0.926843 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "qiu_9.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.880137, v0 = 0.964246, u1 = 0.909491, v1 = 0.99725 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red_dj_1.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 56 },
				uvRect = { u0 = 0.972114, v0 = 0.893839, u1 = 0.999022, v1 = 0.924642 },
				spriteSourceSize = { width = 55, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "red_dj_2.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 11 },
				uvRect = { u0 = 0.905088, v0 = 0.566557, u1 = 0.931996, v1 = 0.572607 },
				spriteSourceSize = { width = 55, height = 13 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "remaining_steps.png",
				spriteColorRect = { x = 0, y = 0, width = 148, height = 75 },
				uvRect = { u0 = 0.932975, v0 = 0.308581, u1 = 0.969667, v1 = 0.389989 },
				spriteSourceSize = { width = 148, height = 75 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "remaining_time.png",
				spriteColorRect = { x = 0, y = 0, width = 148, height = 75 },
				uvRect = { u0 = 0.490705, v0 = 0.852035, u1 = 0.527397, v1 = 0.933443 },
				spriteSourceSize = { width = 148, height = 75 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "remind_arrow_20fps_00001.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 18 },
				uvRect = { u0 = 0.68591, v0 = 0.571507, u1 = 0.697652, v1 = 0.581408 },
				spriteSourceSize = { width = 24, height = 18 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "remind_arrow_20fps_00002.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 18 },
				uvRect = { u0 = 0.67319, v0 = 0.571507, u1 = 0.684932, v1 = 0.581408 },
				spriteSourceSize = { width = 24, height = 18 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "remind_arrow_20fps_00003.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 18 },
				uvRect = { u0 = 0.594423, v0 = 0.466447, u1 = 0.606164, v1 = 0.476348 },
				spriteSourceSize = { width = 24, height = 18 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "remind_effect_20fps_00001.png",
				spriteColorRect = { x = 20, y = 23, width = 88, height = 88 },
				uvRect = { u0 = 0.781311, v0 = 0.683168, u1 = 0.824364, v1 = 0.731573 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "remind_effect_20fps_00002.png",
				spriteColorRect = { x = 15, y = 18, width = 96, height = 96 },
				uvRect = { u0 = 0.783268, v0 = 0.629263, u1 = 0.830235, v1 = 0.682068 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "remind_effect_20fps_00003.png",
				spriteColorRect = { x = 17, y = 19, width = 94, height = 94 },
				uvRect = { u0 = 0.831213, v0 = 0.643014, u1 = 0.877202, v1 = 0.694719 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_arrow_30fps_00001.png",
				spriteColorRect = { x = 41, y = 40, width = 18, height = 18 },
				uvRect = { u0 = 0.898728, v0 = 0.308581, u1 = 0.907534, v1 = 0.318482 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_arrow_30fps_00002.png",
				spriteColorRect = { x = 41, y = 41, width = 18, height = 18 },
				uvRect = { u0 = 0.613014, v0 = 0.19692, u1 = 0.62182, v1 = 0.206821 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_arrow_30fps_00003.png",
				spriteColorRect = { x = 41, y = 41, width = 18, height = 18 },
				uvRect = { u0 = 0.804795, v0 = 0.89714, u1 = 0.813601, v1 = 0.907041 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_arrow_30fps_00004.png",
				spriteColorRect = { x = 41, y = 41, width = 18, height = 18 },
				uvRect = { u0 = 0.804795, v0 = 0.886139, u1 = 0.813601, v1 = 0.89604 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_arrow_30fps_00005.png",
				spriteColorRect = { x = 40, y = 40, width = 20, height = 18 },
				uvRect = { u0 = 0.69863, v0 = 0.571507, u1 = 0.708415, v1 = 0.581408 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_arrow_30fps_00006.png",
				spriteColorRect = { x = 41, y = 40, width = 18, height = 18 },
				uvRect = { u0 = 0.607143, v0 = 0.466447, u1 = 0.615949, v1 = 0.476348 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_effect_30fps_00001.png",
				spriteColorRect = { x = 11, y = 10, width = 78, height = 80 },
				uvRect = { u0 = 0.698141, v0 = 0.725523, u1 = 0.736301, v1 = 0.769527 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_effect_30fps_00002.png",
				spriteColorRect = { x = 11, y = 9, width = 78, height = 82 },
				uvRect = { u0 = 0.73728, v0 = 0.717272, u1 = 0.77544, v1 = 0.762376 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_effect_30fps_00003.png",
				spriteColorRect = { x = 11, y = 9, width = 78, height = 84 },
				uvRect = { u0 = 0.656067, v0 = 0.725523, u1 = 0.697162, v1 = 0.768427 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "select_effect_30fps_00004.png",
				spriteColorRect = { x = 9, y = 10, width = 82, height = 82 },
				uvRect = { u0 = 0.655577, v0 = 0.855886, u1 = 0.695695, v1 = 0.90099 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "select_effect_30fps_00005.png",
				spriteColorRect = { x = 8, y = 10, width = 84, height = 80 },
				uvRect = { u0 = 0.655577, v0 = 0.808581, u1 = 0.694716, v1 = 0.854785 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "select_effect_30fps_00006.png",
				spriteColorRect = { x = 9, y = 10, width = 82, height = 80 },
				uvRect = { u0 = 0.655577, v0 = 0.90209, u1 = 0.695695, v1 = 0.946095 },
				spriteSourceSize = { width = 100, height = 100 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "shanguang_30fps_0001.png",
				spriteColorRect = { x = 0, y = 0, width = 195, height = 101 },
				uvRect = { u0 = 0.723581, v0 = 0.338284, u1 = 0.772994, v1 = 0.445545 },
				spriteSourceSize = { width = 195, height = 101 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "shanguang_30fps_0002.png",
				spriteColorRect = { x = 0, y = 0, width = 209, height = 112 },
				uvRect = { u0 = 0.617417, v0 = 0.466447, u1 = 0.672211, v1 = 0.581408 },
				spriteSourceSize = { width = 209, height = 112 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "shanguang_30fps_0003.png",
				spriteColorRect = { x = 0, y = 0, width = 195, height = 101 },
				uvRect = { u0 = 0.723581, v0 = 0.338284, u1 = 0.772994, v1 = 0.445545 },
				spriteSourceSize = { width = 195, height = 101 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "shanguang_30fps_0004.png",
				spriteColorRect = { x = 0, y = 0, width = 209, height = 112 },
				uvRect = { u0 = 0.617417, v0 = 0.466447, u1 = 0.672211, v1 = 0.581408 },
				spriteSourceSize = { width = 209, height = 112 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "shuoming_1.png",
				spriteColorRect = { x = 0, y = 0, width = 49, height = 58 },
				uvRect = { u0 = 0.970646, v0 = 0.342684, u1 = 0.999022, v1 = 0.369637 },
				spriteSourceSize = { width = 49, height = 58 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "sj_1.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 88 },
				uvRect = { u0 = 0.825342, v0 = 0.69582, u1 = 0.868395, v1 = 0.736524 },
				spriteSourceSize = { width = 74, height = 88 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "sj_di_1.png",
				spriteColorRect = { x = 0, y = 0, width = 483, height = 339 },
				uvRect = { u0 = 0.104697, v0 = 0.340484, u1 = 0.270548, v1 = 0.606161 },
				spriteSourceSize = { width = 483, height = 339 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "sj_di_2.png",
				spriteColorRect = { x = 0, y = 0, width = 158, height = 158 },
				uvRect = { u0 = 0.514188, v0 = 0.609461, u1 = 0.591487, v1 = 0.69637 },
				spriteSourceSize = { width = 158, height = 158 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "super_small.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 53 },
				uvRect = { u0 = 0.367417, v0 = 0.969747, u1 = 0.398728, v1 = 0.9989 },
				spriteSourceSize = { width = 64, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "top_panel.png",
				spriteColorRect = { x = 0, y = 0, width = 640, height = 100 },
				uvRect = { u0 = 0.317515, v0 = 0.140814, u1 = 0.630626, v1 = 0.19582 },
				spriteSourceSize = { width = 640, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tuxing_1.png",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 86 },
				uvRect = { u0 = 0.591977, v0 = 0.951595, u1 = 0.638943, v1 = 0.9989 },
				spriteSourceSize = { width = 96, height = 86 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "tuxing_di_1.png",
				spriteColorRect = { x = 0, y = 0, width = 85, height = 76 },
				uvRect = { u0 = 0.639922, v0 = 0.951595, u1 = 0.677104, v1 = 0.99835 },
				spriteSourceSize = { width = 85, height = 76 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "tuxing_di_2.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 56 },
				uvRect = { u0 = 0.905577, v0 = 0.69967, u1 = 0.932975, v1 = 0.735974 },
				spriteSourceSize = { width = 66, height = 56 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "ui_tishi_guangquan_30fps_00001.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.776419, v0 = 0.732673, u1 = 0.815558, v1 = 0.776678 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_tishi_guangquan_30fps_00002.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.696673, v0 = 0.89879, u1 = 0.735812, v1 = 0.942794 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_tishi_guangquan_30fps_00003.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.696673, v0 = 0.853685, u1 = 0.735812, v1 = 0.89769 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_tishi_guangquan_30fps_00004.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.695695, v0 = 0.808581, u1 = 0.734834, v1 = 0.852585 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_tishi_guangquan_30fps_00005.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.696673, v0 = 0.853685, u1 = 0.735812, v1 = 0.89769 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_tishi_guangquan_30fps_00006.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 80 },
				uvRect = { u0 = 0.696673, v0 = 0.89879, u1 = 0.735812, v1 = 0.942794 },
				spriteSourceSize = { width = 80, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00001.png",
				spriteColorRect = { x = 66, y = 73, width = 62, height = 62 },
				uvRect = { u0 = 0.817515, v0 = 0.780528, u1 = 0.847847, v1 = 0.814631 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00002.png",
				spriteColorRect = { x = 66, y = 73, width = 62, height = 62 },
				uvRect = { u0 = 0.950098, v0 = 0.788229, u1 = 0.980431, v1 = 0.822332 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00003.png",
				spriteColorRect = { x = 63, y = 69, width = 72, height = 74 },
				uvRect = { u0 = 0.869374, v0 = 0.69582, u1 = 0.904599, v1 = 0.736524 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00004.png",
				spriteColorRect = { x = 62, y = 67, width = 76, height = 76 },
				uvRect = { u0 = 0.816536, v0 = 0.737624, u1 = 0.853718, v1 = 0.779428 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00005.png",
				spriteColorRect = { x = 48, y = 54, width = 102, height = 102 },
				uvRect = { u0 = 0.783268, v0 = 0.572057, u1 = 0.83317, v1 = 0.628163 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00006.png",
				spriteColorRect = { x = 46, y = 50, width = 108, height = 108 },
				uvRect = { u0 = 0.517613, v0 = 0.787679, u1 = 0.57045, v1 = 0.847085 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00007.png",
				spriteColorRect = { x = 38, y = 43, width = 124, height = 124 },
				uvRect = { u0 = 0.834149, v0 = 0.573707, u1 = 0.894814, v1 = 0.641914 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00008.png",
				spriteColorRect = { x = 38, y = 43, width = 124, height = 124 },
				uvRect = { u0 = 0.719667, v0 = 0.647965, u1 = 0.780333, v1 = 0.716172 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00009.png",
				spriteColorRect = { x = 21, y = 24, width = 160, height = 160 },
				uvRect = { u0 = 0.853718, v0 = 0.323982, u1 = 0.931996, v1 = 0.411991 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_xiaochu_30fps_00010.png",
				spriteColorRect = { x = 21, y = 24, width = 160, height = 160 },
				uvRect = { u0 = 0.853718, v0 = 0.323982, u1 = 0.931996, v1 = 0.411991 },
				spriteSourceSize = { width = 200, height = 200 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "xt_di_1.png",
				spriteColorRect = { x = 0, y = 0, width = 165, height = 28 },
				uvRect = { u0 = 0.106654, v0 = 0.983498, u1 = 0.187378, v1 = 0.9989 },
				spriteSourceSize = { width = 165, height = 28 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "xt_di_2.png",
				spriteColorRect = { x = 0, y = 0, width = 153, height = 15 },
				uvRect = { u0 = 0.188356, v0 = 0.990649, u1 = 0.263209, v1 = 0.9989 },
				spriteSourceSize = { width = 153, height = 15 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "zhuanhuan_small.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 58 },
				uvRect = { u0 = 0.970646, v0 = 0.308581, u1 = 0.999022, v1 = 0.341584 },
				spriteSourceSize = { width = 60, height = 58 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "zi_1.png",
				spriteColorRect = { x = 0, y = 0, width = 68, height = 36 },
				uvRect = { u0 = 0.978963, v0 = 0.0726073, u1 = 0.996575, v1 = 0.110011 },
				spriteSourceSize = { width = 68, height = 36 },
				spriteTrimmed = false,
				textureRotated = true
			},
		}
	}

