rd /S /Q "../../host/project/assets/lua"
rd /S /Q "../../host/project/assets/pak"
xcopy /S /C /Y /I "../client/lua" "../../host/project/assets/lua"
rd /S /Q "../../host/project/assets/lua/docs"
rd /S /Q "../../host/project/assets/lua/cache"
del /f  "../../host/project/assets/lua\*.bat"
md "../../host/project/assets/pak"
@lua -l config -e "dofile 'src/makepak.lua' ('../client/src', '../../host/project/assets/pak/src')"
@lua -l config -e "dofile 'src/makepak.lua' ('../client/lib', '../../host/project/assets/pak/lib')"
@lua -l config -e "dofile 'src/makepak.lua' ('../base', '../../host/project/assets/pak/base')"
@lua -l config -e "dofile 'src/makeluac.lua' ('../client/init.lua', '../../host/project/assets')"
@lua -l config -e "dofile 'src/makeluac.lua' ('../client/lua/main.lua', '../../host/project/assets/lua')"
@lua -l config -e "dofile 'src/makeluac.lua' ('../base/pakutil.lua', '../../host/project/assets')"
pause