-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:c229eaa6f098864fa4dcff60dc0e30ff:1/1$
-- 

return {
	texture = 'number.atlas.png',
	frames = {
			{
				name = "buynumber_0.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 35 },
				uvRect = { u0 = 0.335938, v0 = 0.464844, u1 = 0.382812, v1 = 0.533203 },
				spriteSourceSize = { width = 24, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_1.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 32 },
				uvRect = { u0 = 0.640625, v0 = 0.384766, u1 = 0.669922, v1 = 0.447266 },
				spriteSourceSize = { width = 15, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_2.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 33 },
				uvRect = { u0 = 0.355469, v0 = 0.607422, u1 = 0.402344, v1 = 0.671875 },
				spriteSourceSize = { width = 24, height = 33 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_3.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 35 },
				uvRect = { u0 = 0.335938, v0 = 0.392578, u1 = 0.380859, v1 = 0.460938 },
				spriteSourceSize = { width = 23, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_4.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 33 },
				uvRect = { u0 = 0.632812, v0 = 0.451172, u1 = 0.677734, v1 = 0.515625 },
				spriteSourceSize = { width = 23, height = 33 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_5.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 32 },
				uvRect = { u0 = 0.408203, v0 = 0.515625, u1 = 0.449219, v1 = 0.578125 },
				spriteSourceSize = { width = 21, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_6.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 35 },
				uvRect = { u0 = 0.304688, v0 = 0.541016, u1 = 0.351562, v1 = 0.609375 },
				spriteSourceSize = { width = 24, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_7.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 33 },
				uvRect = { u0 = 0.304688, v0 = 0.613281, u1 = 0.351562, v1 = 0.677734 },
				spriteSourceSize = { width = 24, height = 33 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_8.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 36 },
				uvRect = { u0 = 0.158203, v0 = 0.925781, u1 = 0.203125, v1 = 0.996094 },
				spriteSourceSize = { width = 23, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buynumber_9.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 34 },
				uvRect = { u0 = 0.386719, v0 = 0.445312, u1 = 0.4375, v1 = 0.511719 },
				spriteSourceSize = { width = 26, height = 34 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "buyprice_0.png",
				spriteColorRect = { x = 1, y = 1, width = 21, height = 29 },
				uvRect = { u0 = 0.693359, v0 = 0.330078, u1 = 0.734375, v1 = 0.386719 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_1.png",
				spriteColorRect = { x = 4, y = 2, width = 13, height = 27 },
				uvRect = { u0 = 0.851562, v0 = 0.460938, u1 = 0.876953, v1 = 0.513672 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_2.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 29 },
				uvRect = { u0 = 0.890625, v0 = 0.353516, u1 = 0.931641, v1 = 0.410156 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_3.png",
				spriteColorRect = { x = 2, y = 1, width = 19, height = 29 },
				uvRect = { u0 = 0.464844, v0 = 0.826172, u1 = 0.501953, v1 = 0.882812 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_4.png",
				spriteColorRect = { x = 2, y = 2, width = 19, height = 27 },
				uvRect = { u0 = 0.832031, v0 = 0.404297, u1 = 0.869141, v1 = 0.457031 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_5.png",
				spriteColorRect = { x = 1, y = 1, width = 19, height = 29 },
				uvRect = { u0 = 0.464844, v0 = 0.765625, u1 = 0.501953, v1 = 0.822266 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_6.png",
				spriteColorRect = { x = 1, y = 1, width = 21, height = 29 },
				uvRect = { u0 = 0.890625, v0 = 0.292969, u1 = 0.931641, v1 = 0.349609 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_7.png",
				spriteColorRect = { x = 3, y = 2, width = 19, height = 27 },
				uvRect = { u0 = 0.464844, v0 = 0.886719, u1 = 0.501953, v1 = 0.939453 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_8.png",
				spriteColorRect = { x = 0, y = 1, width = 21, height = 29 },
				uvRect = { u0 = 0.693359, v0 = 0.269531, u1 = 0.734375, v1 = 0.326172 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "buyprice_9.png",
				spriteColorRect = { x = 1, y = 0, width = 21, height = 29 },
				uvRect = { u0 = 0.408203, v0 = 0.582031, u1 = 0.449219, v1 = 0.638672 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_#.png",
				spriteColorRect = { x = 6, y = 5, width = 18, height = 23 },
				uvRect = { u0 = 0.773438, v0 = 0.453125, u1 = 0.808594, v1 = 0.498047 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_-.png",
				spriteColorRect = { x = 7, y = 11, width = 14, height = 11 },
				uvRect = { u0 = 0.943359, v0 = 0.486328, u1 = 0.970703, v1 = 0.507812 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_0.png",
				spriteColorRect = { x = 7, y = 4, width = 18, height = 25 },
				uvRect = { u0 = 0.8125, v0 = 0.513672, u1 = 0.847656, v1 = 0.5625 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_1.png",
				spriteColorRect = { x = 5, y = 6, width = 14, height = 23 },
				uvRect = { u0 = 0.230469, v0 = 0.814453, u1 = 0.257812, v1 = 0.859375 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_2.png",
				spriteColorRect = { x = 5, y = 4, width = 18, height = 25 },
				uvRect = { u0 = 0.8125, v0 = 0.460938, u1 = 0.847656, v1 = 0.509766 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_3.png",
				spriteColorRect = { x = 9, y = 4, width = 16, height = 25 },
				uvRect = { u0 = 0.851562, v0 = 0.517578, u1 = 0.882812, v1 = 0.566406 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_4.png",
				spriteColorRect = { x = 5, y = 5, width = 20, height = 23 },
				uvRect = { u0 = 0.160156, v0 = 0.876953, u1 = 0.199219, v1 = 0.921875 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_5.png",
				spriteColorRect = { x = 7, y = 6, width = 18, height = 23 },
				uvRect = { u0 = 0.720703, v0 = 0.396484, u1 = 0.755859, v1 = 0.441406 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_6.png",
				spriteColorRect = { x = 6, y = 5, width = 18, height = 23 },
				uvRect = { u0 = 0.261719, v0 = 0.839844, u1 = 0.296875, v1 = 0.884766 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_7.png",
				spriteColorRect = { x = 6, y = 6, width = 18, height = 23 },
				uvRect = { u0 = 0.203125, v0 = 0.876953, u1 = 0.238281, v1 = 0.921875 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_8.png",
				spriteColorRect = { x = 6, y = 4, width = 18, height = 25 },
				uvRect = { u0 = 0.261719, v0 = 0.787109, u1 = 0.296875, v1 = 0.835938 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "enemy_9.png",
				spriteColorRect = { x = 5, y = 4, width = 18, height = 25 },
				uvRect = { u0 = 0.261719, v0 = 0.734375, u1 = 0.296875, v1 = 0.783203 },
				spriteSourceSize = { width = 30, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_#.png",
				spriteColorRect = { x = 0, y = 0, width = 12, height = 27 },
				uvRect = { u0 = 0.880859, v0 = 0.460938, u1 = 0.904297, v1 = 0.513672 },
				spriteSourceSize = { width = 12, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exp_0.png",
				spriteColorRect = { x = 0, y = 1, width = 17, height = 23 },
				uvRect = { u0 = 0.886719, v0 = 0.517578, u1 = 0.919922, v1 = 0.5625 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_1.png",
				spriteColorRect = { x = 2, y = 2, width = 11, height = 21 },
				uvRect = { u0 = 0.972656, v0 = 0.564453, u1 = 0.994141, v1 = 0.605469 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_2.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 23 },
				uvRect = { u0 = 0.746094, v0 = 0.652344, u1 = 0.775391, v1 = 0.697266 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_3.png",
				spriteColorRect = { x = 1, y = 1, width = 15, height = 23 },
				uvRect = { u0 = 0.755859, v0 = 0.603516, u1 = 0.785156, v1 = 0.648438 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_4.png",
				spriteColorRect = { x = 1, y = 2, width = 15, height = 21 },
				uvRect = { u0 = 0.876953, v0 = 0.794922, u1 = 0.90625, v1 = 0.835938 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_5.png",
				spriteColorRect = { x = 0, y = 1, width = 15, height = 23 },
				uvRect = { u0 = 0.722656, v0 = 0.603516, u1 = 0.751953, v1 = 0.648438 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_6.png",
				spriteColorRect = { x = 1, y = 1, width = 15, height = 23 },
				uvRect = { u0 = 0.957031, v0 = 0.515625, u1 = 0.986328, v1 = 0.560547 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_7.png",
				spriteColorRect = { x = 2, y = 2, width = 15, height = 21 },
				uvRect = { u0 = 0.84375, v0 = 0.794922, u1 = 0.873047, v1 = 0.835938 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_8.png",
				spriteColorRect = { x = 1, y = 1, width = 15, height = 23 },
				uvRect = { u0 = 0.943359, v0 = 0.4375, u1 = 0.972656, v1 = 0.482422 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "exp_9.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 23 },
				uvRect = { u0 = 0.923828, v0 = 0.515625, u1 = 0.953125, v1 = 0.560547 },
				spriteSourceSize = { width = 17, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "gk_0.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 32 },
				uvRect = { u0 = 0.160156, v0 = 0.611328, u1 = 0.230469, v1 = 0.673828 },
				spriteSourceSize = { width = 36, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_1.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 32 },
				uvRect = { u0 = 0.207031, v0 = 0.925781, u1 = 0.248047, v1 = 0.988281 },
				spriteSourceSize = { width = 21, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_2.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 32 },
				uvRect = { u0 = 0.935547, v0 = 0.171875, u1 = 0.996094, v1 = 0.234375 },
				spriteSourceSize = { width = 31, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_3.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.507812, v0 = 0.501953, u1 = 0.566406, v1 = 0.564453 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_4.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.935547, v0 = 0.238281, u1 = 0.994141, v1 = 0.300781 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_5.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 32 },
				uvRect = { u0 = 0.570312, v0 = 0.517578, u1 = 0.626953, v1 = 0.580078 },
				spriteSourceSize = { width = 29, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_6.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.570312, v0 = 0.451172, u1 = 0.628906, v1 = 0.513672 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_7.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.578125, v0 = 0.384766, u1 = 0.636719, v1 = 0.447266 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_8.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 32 },
				uvRect = { u0 = 0.507812, v0 = 0.435547, u1 = 0.566406, v1 = 0.498047 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "gk_9.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 32 },
				uvRect = { u0 = 0.935547, v0 = 0.105469, u1 = 0.996094, v1 = 0.167969 },
				spriteSourceSize = { width = 31, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "item_0.png",
				spriteColorRect = { x = 1, y = 1, width = 27, height = 34 },
				uvRect = { u0 = 0.384766, v0 = 0.375, u1 = 0.4375, v1 = 0.441406 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_1.png",
				spriteColorRect = { x = 5, y = 2, width = 19, height = 32 },
				uvRect = { u0 = 0.681641, v0 = 0.585938, u1 = 0.71875, v1 = 0.648438 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_2.png",
				spriteColorRect = { x = 2, y = 2, width = 25, height = 32 },
				uvRect = { u0 = 0.669922, v0 = 0.71875, u1 = 0.71875, v1 = 0.78125 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_3.png",
				spriteColorRect = { x = 3, y = 1, width = 25, height = 34 },
				uvRect = { u0 = 0.355469, v0 = 0.537109, u1 = 0.404297, v1 = 0.603516 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_4.png",
				spriteColorRect = { x = 3, y = 2, width = 25, height = 32 },
				uvRect = { u0 = 0.40625, v0 = 0.708984, u1 = 0.455078, v1 = 0.771484 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_5.png",
				spriteColorRect = { x = 2, y = 3, width = 25, height = 32 },
				uvRect = { u0 = 0.40625, v0 = 0.642578, u1 = 0.455078, v1 = 0.705078 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_6.png",
				spriteColorRect = { x = 1, y = 3, width = 27, height = 32 },
				uvRect = { u0 = 0.507812, v0 = 0.634766, u1 = 0.560547, v1 = 0.697266 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_7.png",
				spriteColorRect = { x = 4, y = 2, width = 25, height = 32 },
				uvRect = { u0 = 0.630859, v0 = 0.519531, u1 = 0.679688, v1 = 0.582031 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_8.png",
				spriteColorRect = { x = 3, y = 1, width = 25, height = 34 },
				uvRect = { u0 = 0.207031, v0 = 0.460938, u1 = 0.255859, v1 = 0.527344 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "item_9.png",
				spriteColorRect = { x = 1, y = 2, width = 27, height = 32 },
				uvRect = { u0 = 0.625, v0 = 0.585938, u1 = 0.677734, v1 = 0.648438 },
				spriteSourceSize = { width = 31, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "jsjc_%.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 21 },
				uvRect = { u0 = 0.835938, v0 = 0.359375, u1 = 0.880859, v1 = 0.400391 },
				spriteSourceSize = { width = 23, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_+.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 15 },
				uvRect = { u0 = 0.429688, v0 = 0.908203, u1 = 0.458984, v1 = 0.9375 },
				spriteSourceSize = { width = 15, height = 15 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_0.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.810547, v0 = 0.796875, u1 = 0.839844, v1 = 0.837891 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_1.png",
				spriteColorRect = { x = 1, y = 0, width = 11, height = 21 },
				uvRect = { u0 = 0.892578, v0 = 0.615234, u1 = 0.914062, v1 = 0.65625 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "jsjc_2.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.876953, v0 = 0.75, u1 = 0.90625, v1 = 0.791016 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_3.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.876953, v0 = 0.705078, u1 = 0.90625, v1 = 0.746094 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_4.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.84375, v0 = 0.75, u1 = 0.873047, v1 = 0.791016 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_5.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.84375, v0 = 0.705078, u1 = 0.873047, v1 = 0.746094 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_6.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.810547, v0 = 0.751953, u1 = 0.839844, v1 = 0.792969 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_7.png",
				spriteColorRect = { x = 0, y = 1, width = 15, height = 19 },
				uvRect = { u0 = 0.679688, v0 = 0.916016, u1 = 0.708984, v1 = 0.953125 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "jsjc_8.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.880859, v0 = 0.660156, u1 = 0.910156, v1 = 0.701172 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jsjc_9.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.847656, v0 = 0.660156, u1 = 0.876953, v1 = 0.701172 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_0.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 52 },
				uvRect = { u0 = 0.00390625, v0 = 0.724609, u1 = 0.0820312, v1 = 0.826172 },
				spriteSourceSize = { width = 40, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_1.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 53 },
				uvRect = { u0 = 0.277344, v0 = 0.203125, u1 = 0.332031, v1 = 0.306641 },
				spriteSourceSize = { width = 28, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_2.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 52 },
				uvRect = { u0 = 0.410156, v0 = 0.00390625, u1 = 0.484375, v1 = 0.105469 },
				spriteSourceSize = { width = 38, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_3.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 52 },
				uvRect = { u0 = 0.566406, v0 = 0.00390625, u1 = 0.638672, v1 = 0.105469 },
				spriteSourceSize = { width = 37, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_4.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 53 },
				uvRect = { u0 = 0.00390625, v0 = 0.617188, u1 = 0.0820312, v1 = 0.720703 },
				spriteSourceSize = { width = 40, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_5.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 53 },
				uvRect = { u0 = 0.488281, v0 = 0.00390625, u1 = 0.5625, v1 = 0.107422 },
				spriteSourceSize = { width = 38, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_6.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 53 },
				uvRect = { u0 = 0.00390625, v0 = 0.509766, u1 = 0.0820312, v1 = 0.613281 },
				spriteSourceSize = { width = 40, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_7.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 53 },
				uvRect = { u0 = 0.00390625, v0 = 0.402344, u1 = 0.0839844, v1 = 0.505859 },
				spriteSourceSize = { width = 41, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_8.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 53 },
				uvRect = { u0 = 0.00390625, v0 = 0.830078, u1 = 0.0800781, v1 = 0.933594 },
				spriteSourceSize = { width = 39, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_da_9.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 52 },
				uvRect = { u0 = 0.324219, v0 = 0.00390625, u1 = 0.40625, v1 = 0.105469 },
				spriteSourceSize = { width = 42, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_0.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 21 },
				uvRect = { u0 = 0.789062, v0 = 0.611328, u1 = 0.822266, v1 = 0.652344 },
				spriteSourceSize = { width = 17, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_1.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 21 },
				uvRect = { u0 = 0.910156, v0 = 0.75, u1 = 0.9375, v1 = 0.791016 },
				spriteSourceSize = { width = 14, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_2.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 20 },
				uvRect = { u0 = 0.691406, v0 = 0.957031, u1 = 0.722656, v1 = 0.996094 },
				spriteSourceSize = { width = 16, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_3.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.814453, v0 = 0.660156, u1 = 0.84375, v1 = 0.701172 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_4.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.876953, v0 = 0.570312, u1 = 0.90625, v1 = 0.611328 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_5.png",
				spriteColorRect = { x = 0, y = 0, width = 13, height = 21 },
				uvRect = { u0 = 0.96875, v0 = 0.785156, u1 = 0.994141, v1 = 0.826172 },
				spriteSourceSize = { width = 13, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_6.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 20 },
				uvRect = { u0 = 0.900391, v0 = 0.839844, u1 = 0.929688, v1 = 0.878906 },
				spriteSourceSize = { width = 15, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_7.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 21 },
				uvRect = { u0 = 0.910156, v0 = 0.705078, u1 = 0.9375, v1 = 0.746094 },
				spriteSourceSize = { width = 14, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_8.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.859375, v0 = 0.615234, u1 = 0.888672, v1 = 0.65625 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "jswz_xiao_9.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 20 },
				uvRect = { u0 = 0.619141, v0 = 0.957031, u1 = 0.652344, v1 = 0.996094 },
				spriteSourceSize = { width = 17, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "kick_0.png",
				spriteColorRect = { x = 1, y = 0, width = 34, height = 32 },
				uvRect = { u0 = 0.160156, v0 = 0.810547, u1 = 0.226562, v1 = 0.873047 },
				spriteSourceSize = { width = 36, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "kick_1.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 32 },
				uvRect = { u0 = 0.714844, v0 = 0.652344, u1 = 0.742188, v1 = 0.714844 },
				spriteSourceSize = { width = 14, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "kick_2.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.441406, v0 = 0.433594, u1 = 0.503906, v1 = 0.496094 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "kick_3.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.511719, v0 = 0.369141, u1 = 0.574219, v1 = 0.431641 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "kick_4.png",
				spriteColorRect = { x = 1, y = 1, width = 34, height = 31 },
				uvRect = { u0 = 0.441406, v0 = 0.369141, u1 = 0.507812, v1 = 0.429688 },
				spriteSourceSize = { width = 36, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "kick_5.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 32 },
				uvRect = { u0 = 0.160156, v0 = 0.744141, u1 = 0.226562, v1 = 0.806641 },
				spriteSourceSize = { width = 36, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "kick_6.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 31 },
				uvRect = { u0 = 0.234375, v0 = 0.605469, u1 = 0.300781, v1 = 0.666016 },
				spriteSourceSize = { width = 34, height = 31 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "kick_7.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 32 },
				uvRect = { u0 = 0.160156, v0 = 0.677734, u1 = 0.226562, v1 = 0.740234 },
				spriteSourceSize = { width = 34, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "kick_8.png",
				spriteColorRect = { x = 0, y = 1, width = 34, height = 31 },
				uvRect = { u0 = 0.234375, v0 = 0.541016, u1 = 0.300781, v1 = 0.601562 },
				spriteSourceSize = { width = 34, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "kick_9.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 32 },
				uvRect = { u0 = 0.0859375, v0 = 0.785156, u1 = 0.15625, v1 = 0.847656 },
				spriteSourceSize = { width = 36, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_%.png",
				spriteColorRect = { x = 0, y = 2, width = 25, height = 19 },
				uvRect = { u0 = 0.626953, v0 = 0.916016, u1 = 0.675781, v1 = 0.953125 },
				spriteSourceSize = { width = 25, height = 21 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "level1_+.png",
				spriteColorRect = { x = 0, y = 1, width = 14, height = 12 },
				uvRect = { u0 = 0.349609, v0 = 0.916016, u1 = 0.376953, v1 = 0.939453 },
				spriteSourceSize = { width = 14, height = 14 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "level1_0.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 17 },
				uvRect = { u0 = 0.859375, v0 = 0.955078, u1 = 0.888672, v1 = 0.988281 },
				spriteSourceSize = { width = 15, height = 17 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_1.png",
				spriteColorRect = { x = 0, y = 0, width = 11, height = 17 },
				uvRect = { u0 = 0.941406, v0 = 0.748047, u1 = 0.962891, v1 = 0.78125 },
				spriteSourceSize = { width = 11, height = 17 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_2.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 17 },
				uvRect = { u0 = 0.855469, v0 = 0.917969, u1 = 0.884766, v1 = 0.951172 },
				spriteSourceSize = { width = 15, height = 17 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_3.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 18 },
				uvRect = { u0 = 0.964844, v0 = 0.878906, u1 = 0.996094, v1 = 0.914062 },
				spriteSourceSize = { width = 16, height = 18 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_4.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 17 },
				uvRect = { u0 = 0.591797, v0 = 0.916016, u1 = 0.623047, v1 = 0.949219 },
				spriteSourceSize = { width = 16, height = 17 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_5.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 17 },
				uvRect = { u0 = 0.826172, v0 = 0.955078, u1 = 0.855469, v1 = 0.988281 },
				spriteSourceSize = { width = 15, height = 17 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_6.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 17 },
				uvRect = { u0 = 0.822266, v0 = 0.917969, u1 = 0.851562, v1 = 0.951172 },
				spriteSourceSize = { width = 17, height = 17 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "level1_7.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 17 },
				uvRect = { u0 = 0.777344, v0 = 0.748047, u1 = 0.806641, v1 = 0.78125 },
				spriteSourceSize = { width = 15, height = 17 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_8.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 18 },
				uvRect = { u0 = 0.964844, v0 = 0.839844, u1 = 0.996094, v1 = 0.875 },
				spriteSourceSize = { width = 16, height = 18 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level1_9.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 18 },
				uvRect = { u0 = 0.556641, v0 = 0.914062, u1 = 0.587891, v1 = 0.949219 },
				spriteSourceSize = { width = 16, height = 18 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level_0.png",
				spriteColorRect = { x = 0, y = 0, width = 11, height = 15 },
				uvRect = { u0 = 0.974609, v0 = 0.917969, u1 = 0.996094, v1 = 0.947266 },
				spriteSourceSize = { width = 11, height = 15 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level_1.png",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 15 },
				uvRect = { u0 = 0.908203, v0 = 0.917969, u1 = 0.919922, v1 = 0.947266 },
				spriteSourceSize = { width = 6, height = 15 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level_2.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 16 },
				uvRect = { u0 = 0.40625, v0 = 0.908203, u1 = 0.425781, v1 = 0.939453 },
				spriteSourceSize = { width = 10, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level_3.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 16 },
				uvRect = { u0 = 0.976562, v0 = 0.480469, u1 = 0.996094, v1 = 0.511719 },
				spriteSourceSize = { width = 10, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level_4.png",
				spriteColorRect = { x = 0, y = 0, width = 11, height = 15 },
				uvRect = { u0 = 0.949219, v0 = 0.917969, u1 = 0.970703, v1 = 0.947266 },
				spriteSourceSize = { width = 11, height = 15 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level_5.png",
				spriteColorRect = { x = 1, y = 0, width = 9, height = 15 },
				uvRect = { u0 = 0.943359, v0 = 0.882812, u1 = 0.960938, v1 = 0.912109 },
				spriteSourceSize = { width = 11, height = 15 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "level_6.png",
				spriteColorRect = { x = 0, y = 0, width = 11, height = 15 },
				uvRect = { u0 = 0.923828, v0 = 0.917969, u1 = 0.945312, v1 = 0.947266 },
				spriteSourceSize = { width = 11, height = 15 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level_7.png",
				spriteColorRect = { x = 2, y = 0, width = 9, height = 15 },
				uvRect = { u0 = 0.947266, v0 = 0.65625, u1 = 0.964844, v1 = 0.685547 },
				spriteSourceSize = { width = 11, height = 15 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "level_8.png",
				spriteColorRect = { x = 0, y = 0, width = 11, height = 15 },
				uvRect = { u0 = 0.917969, v0 = 0.951172, u1 = 0.939453, v1 = 0.980469 },
				spriteSourceSize = { width = 11, height = 15 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "level_9.png",
				spriteColorRect = { x = 0, y = 0, width = 11, height = 15 },
				uvRect = { u0 = 0.892578, v0 = 0.955078, u1 = 0.914062, v1 = 0.984375 },
				spriteSourceSize = { width = 11, height = 15 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lock_0.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 22 },
				uvRect = { u0 = 0.583984, v0 = 0.953125, u1 = 0.615234, v1 = 0.996094 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lock_1.png",
				spriteColorRect = { x = 2, y = 1, width = 10, height = 20 },
				uvRect = { u0 = 0.976562, v0 = 0.4375, u1 = 0.996094, v1 = 0.476562 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lock_2.png",
				spriteColorRect = { x = 1, y = 1, width = 14, height = 20 },
				uvRect = { u0 = 0.96875, v0 = 0.742188, u1 = 0.996094, v1 = 0.78125 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lock_3.png",
				spriteColorRect = { x = 1, y = 0, width = 14, height = 22 },
				uvRect = { u0 = 0.941406, v0 = 0.564453, u1 = 0.96875, v1 = 0.607422 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lock_4.png",
				spriteColorRect = { x = 1, y = 1, width = 14, height = 20 },
				uvRect = { u0 = 0.96875, v0 = 0.699219, u1 = 0.996094, v1 = 0.738281 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lock_5.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 22 },
				uvRect = { u0 = 0.910156, v0 = 0.566406, u1 = 0.9375, v1 = 0.609375 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lock_6.png",
				spriteColorRect = { x = 1, y = 0, width = 14, height = 22 },
				uvRect = { u0 = 0.806641, v0 = 0.841797, u1 = 0.833984, v1 = 0.884766 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lock_7.png",
				spriteColorRect = { x = 2, y = 1, width = 14, height = 20 },
				uvRect = { u0 = 0.96875, v0 = 0.65625, u1 = 0.996094, v1 = 0.695312 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lock_8.png",
				spriteColorRect = { x = 1, y = 0, width = 14, height = 22 },
				uvRect = { u0 = 0.779297, v0 = 0.785156, u1 = 0.806641, v1 = 0.828125 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "lock_9.png",
				spriteColorRect = { x = 1, y = 1, width = 14, height = 20 },
				uvRect = { u0 = 0.933594, v0 = 0.839844, u1 = 0.960938, v1 = 0.878906 },
				spriteSourceSize = { width = 16, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_0.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 52 },
				uvRect = { u0 = 0.712891, v0 = 0.00390625, u1 = 0.779297, v1 = 0.105469 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_1.png",
				spriteColorRect = { x = 4, y = 1, width = 22, height = 50 },
				uvRect = { u0 = 0.535156, v0 = 0.193359, u1 = 0.578125, v1 = 0.291016 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_2.png",
				spriteColorRect = { x = 0, y = 1, width = 32, height = 50 },
				uvRect = { u0 = 0.46875, v0 = 0.193359, u1 = 0.53125, v1 = 0.291016 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_3.png",
				spriteColorRect = { x = 1, y = 0, width = 32, height = 52 },
				uvRect = { u0 = 0.783203, v0 = 0.00390625, u1 = 0.845703, v1 = 0.105469 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_4.png",
				spriteColorRect = { x = 1, y = 1, width = 32, height = 50 },
				uvRect = { u0 = 0.402344, v0 = 0.191406, u1 = 0.464844, v1 = 0.289062 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_5.png",
				spriteColorRect = { x = 0, y = 2, width = 32, height = 50 },
				uvRect = { u0 = 0.335938, v0 = 0.191406, u1 = 0.398438, v1 = 0.289062 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_6.png",
				spriteColorRect = { x = 0, y = 2, width = 34, height = 50 },
				uvRect = { u0 = 0.919922, v0 = 0.00390625, u1 = 0.986328, v1 = 0.101562 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_7.png",
				spriteColorRect = { x = 2, y = 1, width = 32, height = 50 },
				uvRect = { u0 = 0.210938, v0 = 0.203125, u1 = 0.273438, v1 = 0.300781 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_8.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 52 },
				uvRect = { u0 = 0.642578, v0 = 0.00390625, u1 = 0.708984, v1 = 0.105469 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_9.png",
				spriteColorRect = { x = 0, y = 1, width = 34, height = 50 },
				uvRect = { u0 = 0.849609, v0 = 0.00390625, u1 = 0.916016, v1 = 0.101562 },
				spriteSourceSize = { width = 34, height = 52 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_num_0.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.410156, v0 = 0.841797, u1 = 0.460938, v1 = 0.904297 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_1.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 32 },
				uvRect = { u0 = 0.673828, v0 = 0.652344, u1 = 0.710938, v1 = 0.714844 },
				spriteSourceSize = { width = 19, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_2.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.724609, v0 = 0.785156, u1 = 0.775391, v1 = 0.847656 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_3.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.669922, v0 = 0.785156, u1 = 0.720703, v1 = 0.847656 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_4.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.615234, v0 = 0.785156, u1 = 0.666016, v1 = 0.847656 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_5.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.560547, v0 = 0.783203, u1 = 0.611328, v1 = 0.845703 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_6.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.505859, v0 = 0.767578, u1 = 0.556641, v1 = 0.830078 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_7.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.410156, v0 = 0.775391, u1 = 0.460938, v1 = 0.837891 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_8.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.355469, v0 = 0.796875, u1 = 0.40625, v1 = 0.859375 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_num_9.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.300781, v0 = 0.814453, u1 = 0.351562, v1 = 0.876953 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mission_start_0.png",
				spriteColorRect = { x = 1, y = 8, width = 52, height = 49 },
				uvRect = { u0 = 0.21875, v0 = 0.00390625, u1 = 0.320312, v1 = 0.0996094 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_1.png",
				spriteColorRect = { x = 16, y = 8, width = 22, height = 49 },
				uvRect = { u0 = 0.8125, v0 = 0.109375, u1 = 0.855469, v1 = 0.205078 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_2.png",
				spriteColorRect = { x = 2, y = 8, width = 50, height = 49 },
				uvRect = { u0 = 0.21875, v0 = 0.103516, u1 = 0.316406, v1 = 0.199219 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_3.png",
				spriteColorRect = { x = 2, y = 8, width = 50, height = 49 },
				uvRect = { u0 = 0.109375, v0 = 0.203125, u1 = 0.207031, v1 = 0.298828 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_4.png",
				spriteColorRect = { x = 1, y = 8, width = 52, height = 49 },
				uvRect = { u0 = 0.113281, v0 = 0.103516, u1 = 0.214844, v1 = 0.199219 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_5.png",
				spriteColorRect = { x = 2, y = 8, width = 50, height = 49 },
				uvRect = { u0 = 0.00390625, v0 = 0.302734, u1 = 0.101562, v1 = 0.398438 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_6.png",
				spriteColorRect = { x = 1, y = 8, width = 52, height = 49 },
				uvRect = { u0 = 0.00390625, v0 = 0.203125, u1 = 0.105469, v1 = 0.298828 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_7.png",
				spriteColorRect = { x = 0, y = 9, width = 54, height = 49 },
				uvRect = { u0 = 0.00390625, v0 = 0.103516, u1 = 0.109375, v1 = 0.199219 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_8.png",
				spriteColorRect = { x = 1, y = 8, width = 52, height = 49 },
				uvRect = { u0 = 0.113281, v0 = 0.00390625, u1 = 0.214844, v1 = 0.0996094 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mission_start_9.png",
				spriteColorRect = { x = 0, y = 8, width = 54, height = 49 },
				uvRect = { u0 = 0.00390625, v0 = 0.00390625, u1 = 0.109375, v1 = 0.0996094 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "money_0.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 27 },
				uvRect = { u0 = 0.451172, v0 = 0.943359, u1 = 0.496094, v1 = 0.996094 },
				spriteSourceSize = { width = 23, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "money_1.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 27 },
				uvRect = { u0 = 0.775391, v0 = 0.501953, u1 = 0.808594, v1 = 0.554688 },
				spriteSourceSize = { width = 17, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "money_2.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 27 },
				uvRect = { u0 = 0.673828, v0 = 0.390625, u1 = 0.716797, v1 = 0.443359 },
				spriteSourceSize = { width = 22, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "money_3.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 28 },
				uvRect = { u0 = 0.728516, v0 = 0.445312, u1 = 0.769531, v1 = 0.5 },
				spriteSourceSize = { width = 21, height = 28 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "money_4.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 28 },
				uvRect = { u0 = 0.787109, v0 = 0.339844, u1 = 0.832031, v1 = 0.394531 },
				spriteSourceSize = { width = 23, height = 28 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "money_5.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 28 },
				uvRect = { u0 = 0.683594, v0 = 0.511719, u1 = 0.724609, v1 = 0.566406 },
				spriteSourceSize = { width = 21, height = 28 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "money_6.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 28 },
				uvRect = { u0 = 0.738281, v0 = 0.337891, u1 = 0.783203, v1 = 0.392578 },
				spriteSourceSize = { width = 23, height = 28 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "money_7.png",
				spriteColorRect = { x = 0, y = 2, width = 24, height = 27 },
				uvRect = { u0 = 0.302734, v0 = 0.943359, u1 = 0.349609, v1 = 0.996094 },
				spriteSourceSize = { width = 24, height = 29 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "money_8.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 28 },
				uvRect = { u0 = 0.300781, v0 = 0.880859, u1 = 0.345703, v1 = 0.935547 },
				spriteSourceSize = { width = 23, height = 28 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "money_9.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 29 },
				uvRect = { u0 = 0.0371094, v0 = 0.9375, u1 = 0.0820312, v1 = 0.994141 },
				spriteSourceSize = { width = 23, height = 29 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_#.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 32 },
				uvRect = { u0 = 0.458984, v0 = 0.632812, u1 = 0.503906, v1 = 0.695312 },
				spriteSourceSize = { width = 23, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_0.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 32 },
				uvRect = { u0 = 0.566406, v0 = 0.583984, u1 = 0.621094, v1 = 0.646484 },
				spriteSourceSize = { width = 28, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_1.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 32 },
				uvRect = { u0 = 0.0878906, v0 = 0.484375, u1 = 0.126953, v1 = 0.546875 },
				spriteSourceSize = { width = 20, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_2.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.300781, v0 = 0.748047, u1 = 0.351562, v1 = 0.810547 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_3.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.300781, v0 = 0.681641, u1 = 0.351562, v1 = 0.744141 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_4.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 32 },
				uvRect = { u0 = 0.507812, v0 = 0.568359, u1 = 0.5625, v1 = 0.630859 },
				spriteSourceSize = { width = 28, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_5.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.722656, v0 = 0.71875, u1 = 0.773438, v1 = 0.78125 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_6.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.615234, v0 = 0.71875, u1 = 0.666016, v1 = 0.78125 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_7.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.560547, v0 = 0.716797, u1 = 0.611328, v1 = 0.779297 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_8.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.505859, v0 = 0.701172, u1 = 0.556641, v1 = 0.763672 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "monster_9.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.619141, v0 = 0.652344, u1 = 0.669922, v1 = 0.714844 },
				spriteSourceSize = { width = 26, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ogre_0.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 40 },
				uvRect = { u0 = 0.359375, v0 = 0.292969, u1 = 0.4375, v1 = 0.371094 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_1.png",
				spriteColorRect = { x = 10, y = 4, width = 20, height = 40 },
				uvRect = { u0 = 0.0878906, v0 = 0.402344, u1 = 0.126953, v1 = 0.480469 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_2.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 40 },
				uvRect = { u0 = 0.277344, v0 = 0.310547, u1 = 0.355469, v1 = 0.388672 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_3.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 40 },
				uvRect = { u0 = 0.195312, v0 = 0.304688, u1 = 0.273438, v1 = 0.382812 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_4.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 40 },
				uvRect = { u0 = 0.730469, v0 = 0.109375, u1 = 0.808594, v1 = 0.1875 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_5.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 40 },
				uvRect = { u0 = 0.648438, v0 = 0.109375, u1 = 0.726562, v1 = 0.1875 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_6.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 40 },
				uvRect = { u0 = 0.566406, v0 = 0.109375, u1 = 0.644531, v1 = 0.1875 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_7.png",
				spriteColorRect = { x = 0, y = 5, width = 40, height = 40 },
				uvRect = { u0 = 0.484375, v0 = 0.111328, u1 = 0.5625, v1 = 0.189453 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_8.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 40 },
				uvRect = { u0 = 0.402344, v0 = 0.109375, u1 = 0.480469, v1 = 0.1875 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ogre_9.png",
				spriteColorRect = { x = 0, y = 4, width = 40, height = 40 },
				uvRect = { u0 = 0.320312, v0 = 0.109375, u1 = 0.398438, v1 = 0.1875 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_0.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 22 },
				uvRect = { u0 = 0.810547, v0 = 0.705078, u1 = 0.839844, v1 = 0.748047 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_1.png",
				spriteColorRect = { x = 2, y = 0, width = 11, height = 20 },
				uvRect = { u0 = 0.941406, v0 = 0.705078, u1 = 0.962891, v1 = 0.744141 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_2.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 20 },
				uvRect = { u0 = 0.867188, v0 = 0.839844, u1 = 0.896484, v1 = 0.878906 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_3.png",
				spriteColorRect = { x = 2, y = 0, width = 13, height = 22 },
				uvRect = { u0 = 0.917969, v0 = 0.613281, u1 = 0.943359, v1 = 0.65625 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_4.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 20 },
				uvRect = { u0 = 0.792969, v0 = 0.957031, u1 = 0.822266, v1 = 0.996094 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_5.png",
				spriteColorRect = { x = 2, y = 0, width = 13, height = 22 },
				uvRect = { u0 = 0.90625, v0 = 0.414062, u1 = 0.931641, v1 = 0.457031 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_6.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 22 },
				uvRect = { u0 = 0.777344, v0 = 0.701172, u1 = 0.806641, v1 = 0.744141 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_7.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 20 },
				uvRect = { u0 = 0.759766, v0 = 0.957031, u1 = 0.789062, v1 = 0.996094 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_8.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 22 },
				uvRect = { u0 = 0.873047, v0 = 0.414062, u1 = 0.902344, v1 = 0.457031 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_9.png",
				spriteColorRect = { x = 1, y = 0, width = 15, height = 20 },
				uvRect = { u0 = 0.726562, v0 = 0.957031, u1 = 0.755859, v1 = 0.996094 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_0.png",
				spriteColorRect = { x = 0, y = 2, width = 13, height = 21 },
				uvRect = { u0 = 0.939453, v0 = 0.794922, u1 = 0.964844, v1 = 0.835938 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_1.png",
				spriteColorRect = { x = 2, y = 3, width = 7, height = 19 },
				uvRect = { u0 = 0.976562, v0 = 0.609375, u1 = 0.990234, v1 = 0.646484 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_2.png",
				spriteColorRect = { x = 1, y = 3, width = 11, height = 19 },
				uvRect = { u0 = 0.796875, v0 = 0.916016, u1 = 0.818359, v1 = 0.953125 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_3.png",
				spriteColorRect = { x = 1, y = 2, width = 11, height = 21 },
				uvRect = { u0 = 0.759766, v0 = 0.396484, u1 = 0.78125, v1 = 0.4375 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_4.png",
				spriteColorRect = { x = 0, y = 3, width = 13, height = 19 },
				uvRect = { u0 = 0.742188, v0 = 0.916016, u1 = 0.767578, v1 = 0.953125 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_5.png",
				spriteColorRect = { x = 1, y = 4, width = 11, height = 19 },
				uvRect = { u0 = 0.771484, v0 = 0.916016, u1 = 0.792969, v1 = 0.953125 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_6.png",
				spriteColorRect = { x = 0, y = 2, width = 13, height = 21 },
				uvRect = { u0 = 0.837891, v0 = 0.841797, u1 = 0.863281, v1 = 0.882812 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_7.png",
				spriteColorRect = { x = 0, y = 3, width = 13, height = 19 },
				uvRect = { u0 = 0.712891, v0 = 0.916016, u1 = 0.738281, v1 = 0.953125 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_8.png",
				spriteColorRect = { x = 0, y = 2, width = 13, height = 21 },
				uvRect = { u0 = 0.947266, v0 = 0.611328, u1 = 0.972656, v1 = 0.652344 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pet_red_9.png",
				spriteColorRect = { x = 0, y = 2, width = 13, height = 21 },
				uvRect = { u0 = 0.910156, v0 = 0.794922, u1 = 0.935547, v1 = 0.835938 },
				spriteSourceSize = { width = 13, height = 25 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_0.png",
				spriteColorRect = { x = 1, y = 0, width = 24, height = 31 },
				uvRect = { u0 = 0.708984, v0 = 0.851562, u1 = 0.755859, v1 = 0.912109 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_1.png",
				spriteColorRect = { x = 2, y = 0, width = 18, height = 31 },
				uvRect = { u0 = 0.261719, v0 = 0.669922, u1 = 0.296875, v1 = 0.730469 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_2.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 31 },
				uvRect = { u0 = 0.658203, v0 = 0.851562, u1 = 0.705078, v1 = 0.912109 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_3.png",
				spriteColorRect = { x = 2, y = 0, width = 22, height = 31 },
				uvRect = { u0 = 0.681641, v0 = 0.447266, u1 = 0.724609, v1 = 0.507812 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_4.png",
				spriteColorRect = { x = 1, y = 0, width = 24, height = 31 },
				uvRect = { u0 = 0.607422, v0 = 0.851562, u1 = 0.654297, v1 = 0.912109 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_5.png",
				spriteColorRect = { x = 2, y = 0, width = 22, height = 31 },
				uvRect = { u0 = 0.759766, v0 = 0.851562, u1 = 0.802734, v1 = 0.912109 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_6.png",
				spriteColorRect = { x = 1, y = 0, width = 24, height = 31 },
				uvRect = { u0 = 0.556641, v0 = 0.849609, u1 = 0.603516, v1 = 0.910156 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_7.png",
				spriteColorRect = { x = 3, y = 0, width = 22, height = 31 },
				uvRect = { u0 = 0.8125, v0 = 0.208984, u1 = 0.855469, v1 = 0.269531 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_8.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 31 },
				uvRect = { u0 = 0.505859, v0 = 0.833984, u1 = 0.552734, v1 = 0.894531 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "role_9.png",
				spriteColorRect = { x = 1, y = 0, width = 24, height = 31 },
				uvRect = { u0 = 0.355469, v0 = 0.732422, u1 = 0.402344, v1 = 0.792969 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rw_sz_#.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 30 },
				uvRect = { u0 = 0.00390625, v0 = 0.9375, u1 = 0.0332031, v1 = 0.996094 },
				spriteSourceSize = { width = 15, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_(.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 33 },
				uvRect = { u0 = 0.230469, v0 = 0.746094, u1 = 0.257812, v1 = 0.810547 },
				spriteSourceSize = { width = 16, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rw_sz_).png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 33 },
				uvRect = { u0 = 0.230469, v0 = 0.677734, u1 = 0.257812, v1 = 0.742188 },
				spriteSourceSize = { width = 16, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rw_sz_0.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 27 },
				uvRect = { u0 = 0.402344, v0 = 0.943359, u1 = 0.447266, v1 = 0.996094 },
				spriteSourceSize = { width = 23, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_1.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 26 },
				uvRect = { u0 = 0.908203, v0 = 0.460938, u1 = 0.939453, v1 = 0.511719 },
				spriteSourceSize = { width = 16, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_2.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 26 },
				uvRect = { u0 = 0.785156, v0 = 0.398438, u1 = 0.828125, v1 = 0.449219 },
				spriteSourceSize = { width = 22, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_3.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 26 },
				uvRect = { u0 = 0.505859, v0 = 0.898438, u1 = 0.552734, v1 = 0.949219 },
				spriteSourceSize = { width = 24, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_4.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 25 },
				uvRect = { u0 = 0.355469, v0 = 0.863281, u1 = 0.402344, v1 = 0.912109 },
				spriteSourceSize = { width = 24, height = 25 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_5.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 27 },
				uvRect = { u0 = 0.353516, v0 = 0.943359, u1 = 0.398438, v1 = 0.996094 },
				spriteSourceSize = { width = 23, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_6.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 26 },
				uvRect = { u0 = 0.251953, v0 = 0.888672, u1 = 0.296875, v1 = 0.939453 },
				spriteSourceSize = { width = 23, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_7.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 26 },
				uvRect = { u0 = 0.728516, v0 = 0.503906, u1 = 0.771484, v1 = 0.554688 },
				spriteSourceSize = { width = 22, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_8.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 27 },
				uvRect = { u0 = 0.251953, v0 = 0.943359, u1 = 0.298828, v1 = 0.996094 },
				spriteSourceSize = { width = 24, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_9.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 27 },
				uvRect = { u0 = 0.355469, v0 = 0.675781, u1 = 0.402344, v1 = 0.728516 },
				spriteSourceSize = { width = 24, height = 27 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rw_sz_x.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 22 },
				uvRect = { u0 = 0.5, v0 = 0.953125, u1 = 0.542969, v1 = 0.996094 },
				spriteSourceSize = { width = 22, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sh1_-.png",
				spriteColorRect = { x = 2, y = 3, width = 34, height = 16 },
				uvRect = { u0 = 0.583984, v0 = 0.349609, u1 = 0.650391, v1 = 0.380859 },
				spriteSourceSize = { width = 36, height = 20 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh1_0.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 36 },
				uvRect = { u0 = 0.441406, v0 = 0.294922, u1 = 0.527344, v1 = 0.365234 },
				spriteSourceSize = { width = 44, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sh1_1.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 36 },
				uvRect = { u0 = 0.53125, v0 = 0.294922, u1 = 0.580078, v1 = 0.365234 },
				spriteSourceSize = { width = 25, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sh1_2.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 36 },
				uvRect = { u0 = 0.0839844, v0 = 0.851562, u1 = 0.15625, v1 = 0.921875 },
				spriteSourceSize = { width = 39, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh1_3.png",
				spriteColorRect = { x = 2, y = 0, width = 35, height = 36 },
				uvRect = { u0 = 0.0859375, v0 = 0.925781, u1 = 0.154297, v1 = 0.996094 },
				spriteSourceSize = { width = 39, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh1_4.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 36 },
				uvRect = { u0 = 0.259766, v0 = 0.466797, u1 = 0.332031, v1 = 0.537109 },
				spriteSourceSize = { width = 39, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh1_5.png",
				spriteColorRect = { x = 1, y = 0, width = 37, height = 36 },
				uvRect = { u0 = 0.130859, v0 = 0.460938, u1 = 0.203125, v1 = 0.53125 },
				spriteSourceSize = { width = 39, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh1_6.png",
				spriteColorRect = { x = 1, y = 0, width = 37, height = 36 },
				uvRect = { u0 = 0.259766, v0 = 0.392578, u1 = 0.332031, v1 = 0.462891 },
				spriteSourceSize = { width = 39, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh1_7.png",
				spriteColorRect = { x = 2, y = 0, width = 37, height = 36 },
				uvRect = { u0 = 0.183594, v0 = 0.386719, u1 = 0.255859, v1 = 0.457031 },
				spriteSourceSize = { width = 39, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh1_8.png",
				spriteColorRect = { x = 2, y = 0, width = 37, height = 36 },
				uvRect = { u0 = 0.859375, v0 = 0.183594, u1 = 0.931641, v1 = 0.253906 },
				spriteSourceSize = { width = 39, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh1_9.png",
				spriteColorRect = { x = 0, y = 2, width = 36, height = 37 },
				uvRect = { u0 = 0.160156, v0 = 0.535156, u1 = 0.230469, v1 = 0.607422 },
				spriteSourceSize = { width = 36, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_-.png",
				spriteColorRect = { x = 1, y = 2, width = 33, height = 16 },
				uvRect = { u0 = 0.859375, v0 = 0.257812, u1 = 0.923828, v1 = 0.289062 },
				spriteSourceSize = { width = 35, height = 20 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_0.png",
				spriteColorRect = { x = 1, y = 0, width = 44, height = 39 },
				uvRect = { u0 = 0.105469, v0 = 0.302734, u1 = 0.191406, v1 = 0.378906 },
				spriteSourceSize = { width = 46, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_1.png",
				spriteColorRect = { x = 0, y = 1, width = 25, height = 38 },
				uvRect = { u0 = 0.130859, v0 = 0.382812, u1 = 0.179688, v1 = 0.457031 },
				spriteSourceSize = { width = 27, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_2.png",
				spriteColorRect = { x = 1, y = 0, width = 36, height = 39 },
				uvRect = { u0 = 0.738281, v0 = 0.191406, u1 = 0.808594, v1 = 0.267578 },
				spriteSourceSize = { width = 38, height = 41 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_3.png",
				spriteColorRect = { x = 0, y = 1, width = 36, height = 38 },
				uvRect = { u0 = 0.0859375, v0 = 0.707031, u1 = 0.15625, v1 = 0.78125 },
				spriteSourceSize = { width = 38, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_4.png",
				spriteColorRect = { x = 0, y = 1, width = 36, height = 38 },
				uvRect = { u0 = 0.0859375, v0 = 0.628906, u1 = 0.15625, v1 = 0.703125 },
				spriteSourceSize = { width = 36, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_5.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 38 },
				uvRect = { u0 = 0.859375, v0 = 0.105469, u1 = 0.931641, v1 = 0.179688 },
				spriteSourceSize = { width = 39, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_6.png",
				spriteColorRect = { x = 0, y = 1, width = 36, height = 38 },
				uvRect = { u0 = 0.0859375, v0 = 0.550781, u1 = 0.15625, v1 = 0.625 },
				spriteSourceSize = { width = 36, height = 42 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_7.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 39 },
				uvRect = { u0 = 0.582031, v0 = 0.191406, u1 = 0.65625, v1 = 0.267578 },
				spriteSourceSize = { width = 40, height = 39 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_8.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 38 },
				uvRect = { u0 = 0.660156, v0 = 0.191406, u1 = 0.734375, v1 = 0.265625 },
				spriteSourceSize = { width = 40, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sh_9.png",
				spriteColorRect = { x = 1, y = 1, width = 36, height = 38 },
				uvRect = { u0 = 0.583984, v0 = 0.271484, u1 = 0.654297, v1 = 0.345703 },
				spriteSourceSize = { width = 38, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_0.png",
				spriteColorRect = { x = 1, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.564453, v0 = 0.650391, u1 = 0.615234, v1 = 0.712891 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_1.png",
				spriteColorRect = { x = 5, y = 0, width = 16, height = 32 },
				uvRect = { u0 = 0.658203, v0 = 0.271484, u1 = 0.689453, v1 = 0.333984 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_2.png",
				spriteColorRect = { x = 2, y = 0, width = 24, height = 32 },
				uvRect = { u0 = 0.935547, v0 = 0.371094, u1 = 0.982422, v1 = 0.433594 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_3.png",
				spriteColorRect = { x = 2, y = 0, width = 24, height = 32 },
				uvRect = { u0 = 0.935547, v0 = 0.304688, u1 = 0.982422, v1 = 0.367188 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_4.png",
				spriteColorRect = { x = 2, y = 0, width = 24, height = 32 },
				uvRect = { u0 = 0.839844, v0 = 0.292969, u1 = 0.886719, v1 = 0.355469 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_5.png",
				spriteColorRect = { x = 3, y = 0, width = 22, height = 32 },
				uvRect = { u0 = 0.458984, v0 = 0.699219, u1 = 0.501953, v1 = 0.761719 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_6.png",
				spriteColorRect = { x = 1, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.453125, v0 = 0.566406, u1 = 0.503906, v1 = 0.628906 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_7.png",
				spriteColorRect = { x = 4, y = 0, width = 24, height = 32 },
				uvRect = { u0 = 0.789062, v0 = 0.273438, u1 = 0.835938, v1 = 0.335938 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_8.png",
				spriteColorRect = { x = 2, y = 0, width = 24, height = 32 },
				uvRect = { u0 = 0.738281, v0 = 0.271484, u1 = 0.785156, v1 = 0.333984 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "stage_9.png",
				spriteColorRect = { x = 1, y = 0, width = 26, height = 32 },
				uvRect = { u0 = 0.453125, v0 = 0.5, u1 = 0.503906, v1 = 0.5625 },
				spriteSourceSize = { width = 30, height = 32 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "timing_$.png",
				spriteColorRect = { x = 1, y = 0, width = 8, height = 17 },
				uvRect = { u0 = 0.888672, v0 = 0.917969, u1 = 0.904297, v1 = 0.951172 },
				spriteSourceSize = { width = 10, height = 17 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "timing_0.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 21 },
				uvRect = { u0 = 0.839844, v0 = 0.570312, u1 = 0.873047, v1 = 0.611328 },
				spriteSourceSize = { width = 17, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_1.png",
				spriteColorRect = { x = 0, y = 0, width = 14, height = 21 },
				uvRect = { u0 = 0.914062, v0 = 0.660156, u1 = 0.941406, v1 = 0.701172 },
				spriteSourceSize = { width = 14, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_2.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 20 },
				uvRect = { u0 = 0.65625, v0 = 0.957031, u1 = 0.6875, v1 = 0.996094 },
				spriteSourceSize = { width = 16, height = 20 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_3.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 21 },
				uvRect = { u0 = 0.779297, v0 = 0.65625, u1 = 0.810547, v1 = 0.697266 },
				spriteSourceSize = { width = 16, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_4.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 21 },
				uvRect = { u0 = 0.802734, v0 = 0.566406, u1 = 0.835938, v1 = 0.607422 },
				spriteSourceSize = { width = 17, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_5.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 22 },
				uvRect = { u0 = 0.546875, v0 = 0.953125, u1 = 0.580078, v1 = 0.996094 },
				spriteSourceSize = { width = 17, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_6.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 21 },
				uvRect = { u0 = 0.765625, v0 = 0.558594, u1 = 0.798828, v1 = 0.599609 },
				spriteSourceSize = { width = 17, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_7.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 21 },
				uvRect = { u0 = 0.826172, v0 = 0.615234, u1 = 0.855469, v1 = 0.65625 },
				spriteSourceSize = { width = 15, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_8.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 21 },
				uvRect = { u0 = 0.728516, v0 = 0.558594, u1 = 0.761719, v1 = 0.599609 },
				spriteSourceSize = { width = 17, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "timing_9.png",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 21 },
				uvRect = { u0 = 0.658203, v0 = 0.337891, u1 = 0.689453, v1 = 0.378906 },
				spriteSourceSize = { width = 16, height = 21 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

